[build]
builder = "NIXPACKS"

[build.nixpacksConfig]
nixPacksVersion = "1.0.0"

[deploy]
startCommand = "cargo run --release --bin server"

[variables]
PORT = "3000"

# Environment variables
[env]
NODE_ENV = "production"
RUST_LOG = "info" 